ARG RUBY_VERSION=3.2.0
ARG APPDIR=/rails
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR ${APPDIR}
ENV BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle"

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives


FROM base as build

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile* ${APPDIR}/

RUN gem install bundler -v 2.6.2 && bundle config --local build.sassc --disable-march-tune-namtive

COPY . .

FROM base

# Copy built artifacts: gems, application
COPY ./app ${APPDIR}/app
COPY ./bin ${APPDIR}/bin
COPY ./config ${APPDIR}/config
COPY ./Rakefile ${APPDIR}/Rakefile
COPY ./lib ${APPDIR}/lib
COPY ./db ${APPDIR}/db
COPY ./config.ru ${APPDIR}/config.ru
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build "${APPDIR}" "${APPDIR}"

RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp